In [3]:
import pandas as pd 
import numpy as np

In [4]:
data = pd.read_csv("heart.csv")

In [5]:
data.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [6]:
data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [8]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [9]:
data.sex.value_counts()

sex
1    713
0    312
Name: count, dtype: int64

In [10]:
pd.crosstab(data.sex, data.target)

target    0    1
sex             
0        86  226
1       413  300

In [11]:
data.shape

(1025, 14)

In [12]:
data.drop_duplicates()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0      1.0   
1     53    1   0       140   203    1        0      155      1      3.1   
2     70    1   0       145   174    0        1      125      1      2.6   
3     61    1   0       148   203    0        1      161      0      0.0   
4     62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0      1.5   
733   44    0   2       108   141    0        1      175      0      0.6   
739   52    1   0       128   255    0        1      161      1      0.0   
843   59    1   3       160   273    0        0      125      0      0.0   
878   54    1   0       120   188    0        1      113      0      1.4   

     slope  ca  thal  target  
0        2   2     3       0  
1        0   0     3       0  
2        0   0     3       0  
3        2   1     3       0  
4        1   3     2       0  
..     ...  ..   ...     ...  
723      1   0     2       1  
733      1   0     2       1  
739      2   1     3       0  
843      2   0     2       0  
878      1   1     3       0  

[302 rows x 14 columns]

In [13]:
data["target"].unique()

array([0, 1], dtype=int64)

In [14]:
print(data.corr()["target"].abs().sort_values(ascending=False))

target      1.000000
oldpeak     0.438441
exang       0.438029
cp          0.434854
thalach     0.422895
ca          0.382085
slope       0.345512
thal        0.337838
sex         0.279501
age         0.229324
trestbps    0.138772
restecg     0.134468
chol        0.099966
fbs         0.041164
Name: target, dtype: float64


In [15]:
data["cp"].unique()

array([0, 1, 2, 3], dtype=int64)

In [16]:
data["fbs"].describe()

count    1025.000000
mean        0.149268
std         0.356527
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: fbs, dtype: float64

In [17]:
data["fbs"].unique()

array([0, 1], dtype=int64)

In [18]:
average_age = data['age'].mean()
print("Average age:", average_age)

Average age: 54.43414634146342


In [19]:
gender_distribution = data['sex'].value_counts()
print("Gender distribution:\n", gender_distribution)

Gender distribution:
 sex
1    713
0    312
Name: count, dtype: int64


In [21]:
high_blood_pressure_count = data[data['trestbps'] > 140].shape[0]
print("Number of individuals with resting blood pressure > 140:", high_blood_pressure_count)

Number of individuals with resting blood pressure > 140: 217


In [22]:
average_cholesterol_cp2 = data[data['cp'] == 2]['chol'].mean()
print("Average cholesterol level among individuals with chest pain type 2:", average_cholesterol_cp2)

Average cholesterol level among individuals with chest pain type 2: 242.19718309859155


In [23]:
max_heart_rate_fbs_gt_120 = data[data['fbs'] > 120]['thalach'].max()
print("Maximum heart rate achieved among individuals with fasting blood sugar > 120:", max_heart_rate_fbs_gt_120)

Maximum heart rate achieved among individuals with fasting blood sugar > 120: nan


In [25]:
high_oldpeak_exang_count = data[(data['exang'] == 1) & (data['oldpeak'] > 2)].shape[0]
print("Number of individuals with exang and oldpeak > 2:", high_oldpeak_exang_count)

Number of individuals with exang and oldpeak > 2: 106


In [26]:
slope_1_proportion = (data['slope'] == 1).mean() * 100
print("Proportion of individuals with slope equal to 1:", slope_1_proportion)

Proportion of individuals with slope equal to 1: 47.02439024390244


In [27]:
thal_type_2_count = data[data['thal'] == 2].shape[0]
print("Number of individuals with thal type 2:", thal_type_2_count)

Number of individuals with thal type 2: 544


In [28]:
target_1_proportion = (data['target'] == 1).mean() * 100
print("Proportion of individuals with target variable equal to 1:", target_1_proportion)

Proportion of individuals with target variable equal to 1: 51.31707317073171
